### ISSUE TITLE
Sharing Results from Monto Carlo Renderings

### ISSUE THREAD

**Issue by hussain7** [joeylitalien/noise2noise-pytorch#6]
Hi ,

Can you please share the results of Monte Carlo Renderings N2N ? 

Regards
Muzahid

**Comment by joeylitalien** [comment]
Hi Muzahid,

I do not have any results for MC rendering denoising. I was hoping to get it to work when I was working on the project, but I couldn't get any satisfying denoised images and moved onto other projects. This is probably due to an error in my implementation, which I have already noted in the [Known Issues](https://github.com/joeylitalien/noise2noise-pytorch#known-issues) section of the main read-me.

Best,
J.
