### ISSUE TITLE
Confused about the unet.py code, is it reasonable?

### ISSUE THREAD

**Issue by amazingyyc** [joeylitalien/noise2noise-pytorch#7]
Hi I checked the code feel confused with the code in unet.py:
```
    def forward(self, x):
        """Through encoder, then decoder by adding U-skip connections. """

        # Encoder
        pool1 = self._block1(x)
        pool2 = self._block2(pool1)
        pool3 = self._block2(pool2)
        pool4 = self._block2(pool3)
        pool5 = self._block2(pool4)
```

pool2-pool5 is computed by self._block2, So it means pool2-pool5 re-use the same conv weight and bias. Does it accepted? I think the u-net should use different conv weight of different layer.

**Comment by joeylitalien** [comment]
Yes, I am aware. This issue was also raised by other people. Although this should be trivial to fix, I do not have the time to rewrite it and test it properly. I'll be happy to accept a pull request if you want to submit one. In the meantime, I've added it to the list of [Known Issues](https://github.com/joeylitalien/noise2noise-pytorch#known-issues).
